esphome:
  name: "test-node"

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

substitutions:
  mac_boiler: XX:XX:XX:XX:XX:XX
  mqtt_broker: 192.168.1.100

external_components:
  - source: 
      type: git
      url: https://github.com/pedobry/esphome-smartboiler
    components: [smartboiler]

mqtt:
  broker: ${mqtt_broker}

ble_client:
  - mac_address: ${mac_boiler}
    id: drazice_okhe

smartboiler:
  - ble_client_id: drazice_okhe
    temp1:
      name: "Boiler temp1"
    temp2:
      name: "Boiler temp2"
    mode:
      name: "Boiler mode"
    thermostat:
      name: "Boiler thermostat"
    heat_on:
      name: "Boiler heat"
    hdo_low_tariff:
      name: "Boiler HDO"
    pin:
      name: "Boiler PIN"
    state:
      name: "Boiler state"
    version:
      name: "Boiler version"
    b_name:
      name: "Boiler name"
    consumption:
      name: "Boiler energy"

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: boiler_wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: boiler_wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"

switch:
  - platform: ble_client
    ble_client_id: drazice_okhe
    name: "Enable boiler monitoring"

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi1_ssid
  password: !secret wifi1_psk


