substitutions:
  mac_address: F2:30:EC:1E:B7:E3
  mqtt_broker: 10.10.10.3

external_components:
  - source:
      type: local
      path: components

mqtt:
  broker: ${mqtt_broker}

sensor:

binary_sensor:

select:

climate:

esp32_ble_tracker:

ble_client:
  - mac_address: ${mac_address}
    id: drazice_okhe

smartboiler:
  ble_client_id: drazice_okhe
  topic_prefix: smartboiler
  temp1:
    name: boiler_temp1
  temp2:
    name: boiler_temp2
  hdo_low_tariff:
    name: hdo_low_tariff
  heat_on:
    name: boiler_heat_on
  mode:
    name: boiler_mode
  thermostat:
    name: boiler_thermostat
  consumption:
    name: boiler_consumption
    state_class: total_increasing
    device_class: energy
